apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercise-tracker-frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: vijaygenius123/exercise-tracker-frontend
          imagePullPolicy: Always
          name: backend
          ports:
            - containerPort: 8000
